import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col">
        <header className="flex items-center justify-between p-4">
          <nav className="flex items-center">
            <Link href={"/"} className="text-xl font-semibold">
              Humming Bird
            </Link>
          </nav>
          <div className="space-x-4">
            <Link
              href={"/user"}
              className="rounded-md border border-transparent px-4 py-1 hover:border-indigo-700 hover:text-indigo-700"
            >
              Add Writer
            </Link>
            <Link
              href={"/lyrics"}
              className="rounded-md border border-transparent px-4 py-1 hover:border-indigo-700 hover:text-indigo-700"
            >
              Add Lyrics
            </Link>
            <Link
              href={"/category"}
              className="rounded-md border border-transparent px-4 py-1 hover:border-indigo-700 hover:text-indigo-700"
            >
              Add Category
            </Link>
          </div>
        </header>
        <main className="flex flex-1 flex-col p-4">{children}</main>
      </body>
    </html>
  );
}
